<?php
/**
 * @file
 * openpublic_blog_demo.features.content.inc
 */

/**
 * Implements hook_content_defaults().
 */
function openpublic_blog_demo_content_defaults() {
  $content = array();

  $content['abc_agency_releases_public_datasets_online'] = (object) array(
    'exported_path' => 'blog/2010-12-30/abc-agency-releases-public-datasets-online',
    'title' => 'ABC Agency releases Public Datasets Online',
    'status' => 1,
    'promote' => 1,
    'sticky' => 0,
    'type' => 'blog_entry',
    'language' => 'und',
    'created' => 1293721196,
    'comment' => 2,
    'translate' => 0,
    'machine_name' => 'abc_agency_releases_public_datasets_online',
    'body' => array(
      'und' => array(
        0 => array(
          'value' => 'Volutpat quam ut quarta mutationem dolore. Eu odio ullamcorper eodem demonstraverunt dolor. Illum quam qui demonstraverunt insitam nulla. Aliquam mirum notare fiant futurum aliquip. Lius ut vel ullamcorper dolor consequat. Sit dolor consuetudium vel quinta wisi. Decima sequitur sollemnes quarta sit ullamcorper. Anteposuerit sequitur veniam est putamus possim. Nam vel suscipit habent humanitatis doming. Option consequat delenit dolore decima amet. Quis magna qui nam non soluta. Sit notare sequitur veniam facit feugait. Facilisis nunc dolor in claritas nunc. Adipiscing magna erat consectetuer usus esse. 

At molestie quis vulputate zzril parum. Investigationes possim adipiscing formas per zzril. Vero dolor fiant est wisi odio. Possim legere nulla option iriure dolore. Dolore parum nisl demonstraverunt id saepius. Tincidunt claritatem quod quam in eum. Dolore parum seacula nonummy parum qui. Eodem nobis claritas consequat modo notare. Doming vel in option ea in. Ipsum in mirum possim et tempor. Augue ut et litterarum insitam ea. Legentis congue accumsan humanitatis decima quam. Ut laoreet dolor eros in lorem. Assum augue legentis elit typi lectorum. 

Quinta augue iusto lobortis claritatem nihil. Illum claritatem adipiscing tation demonstraverunt dynamicus. Facit exerci putamus molestie sit insitam. Facit tincidunt tincidunt at saepius sequitur. Autem doming iis commodo laoreet modo. In gothica habent typi doming dolor. Notare demonstraverunt quam facit habent duis. Nam elit et decima et wisi. Eu euismod eodem modo ad in. Assum diam facer sollemnes Investigationes usus. Volutpat lobortis quam laoreet usus nunc. Laoreet in in gothica in lius. In quod mutationem odio dolore est. Mirum iriure soluta te possim aliquip. 

In duis suscipit typi vero option. Vel humanitatis anteposuerit legere mutationem tation. Quam typi claritatem dignissim id assum. Quod dynamicus ii nibh wisi legentis. Qui nunc feugiat claritatem vel demonstraverunt. Seacula feugait quis wisi sollemnes legere. Dynamicus magna me demonstraverunt ullamcorper vero. Iriure vel eorum sequitur putamus parum. Luptatum decima velit eleifend lectorum eodem. Facer nulla aliquam est vulputate aliquip. Placerat gothica zzril illum modo Investigationes. Ii velit possim legere quis iis. Dolore processus litterarum ullamcorper typi consequat. Usus ad ut sit nibh laoreet. 

Autem habent possim erat lius typi. Sollemnes littera nostrud veniam nulla modo. Nostrud diam vel est nonummy qui. Vel iis humanitatis illum Investigationes in. Dynamicus diam illum in processus typi. Decima mazim enim insitam anteposuerit litterarum.',
          'summary' => '',
          'format' => 'filtered_html',
          'safe_value' => '<p>Volutpat quam ut quarta mutationem dolore. Eu odio ullamcorper eodem demonstraverunt dolor. Illum quam qui demonstraverunt insitam nulla. Aliquam mirum notare fiant futurum aliquip. Lius ut vel ullamcorper dolor consequat. Sit dolor consuetudium vel quinta wisi. Decima sequitur sollemnes quarta sit ullamcorper. Anteposuerit sequitur veniam est putamus possim. Nam vel suscipit habent humanitatis doming. Option consequat delenit dolore decima amet. Quis magna qui nam non soluta. Sit notare sequitur veniam facit feugait. Facilisis nunc dolor in claritas nunc. Adipiscing magna erat consectetuer usus esse. </p>
<p>At molestie quis vulputate zzril parum. Investigationes possim adipiscing formas per zzril. Vero dolor fiant est wisi odio. Possim legere nulla option iriure dolore. Dolore parum nisl demonstraverunt id saepius. Tincidunt claritatem quod quam in eum. Dolore parum seacula nonummy parum qui. Eodem nobis claritas consequat modo notare. Doming vel in option ea in. Ipsum in mirum possim et tempor. Augue ut et litterarum insitam ea. Legentis congue accumsan humanitatis decima quam. Ut laoreet dolor eros in lorem. Assum augue legentis elit typi lectorum. </p>
<p>Quinta augue iusto lobortis claritatem nihil. Illum claritatem adipiscing tation demonstraverunt dynamicus. Facit exerci putamus molestie sit insitam. Facit tincidunt tincidunt at saepius sequitur. Autem doming iis commodo laoreet modo. In gothica habent typi doming dolor. Notare demonstraverunt quam facit habent duis. Nam elit et decima et wisi. Eu euismod eodem modo ad in. Assum diam facer sollemnes Investigationes usus. Volutpat lobortis quam laoreet usus nunc. Laoreet in in gothica in lius. In quod mutationem odio dolore est. Mirum iriure soluta te possim aliquip. </p>
<p>In duis suscipit typi vero option. Vel humanitatis anteposuerit legere mutationem tation. Quam typi claritatem dignissim id assum. Quod dynamicus ii nibh wisi legentis. Qui nunc feugiat claritatem vel demonstraverunt. Seacula feugait quis wisi sollemnes legere. Dynamicus magna me demonstraverunt ullamcorper vero. Iriure vel eorum sequitur putamus parum. Luptatum decima velit eleifend lectorum eodem. Facer nulla aliquam est vulputate aliquip. Placerat gothica zzril illum modo Investigationes. Ii velit possim legere quis iis. Dolore processus litterarum ullamcorper typi consequat. Usus ad ut sit nibh laoreet. </p>
<p>Autem habent possim erat lius typi. Sollemnes littera nostrud veniam nulla modo. Nostrud diam vel est nonummy qui. Vel iis humanitatis illum Investigationes in. Dynamicus diam illum in processus typi. Decima mazim enim insitam anteposuerit litterarum.</p>
',
          'safe_summary' => '',
        ),
      ),
    ),
    'field_topic' => array(
      'und' => array(
        0 => array(
          'vocabulary_machine_name' => 'topic',
          'name' => 'ABC agency',
        ),
      ),
    ),
  );

return $content;
}
